name:Node.js CI
on:
  push:
    branches:[main,developer1,developer2,developer3]
 pull_request:
   branches:[main]

 jobs:
   build:
     runs-on:windows-11


    steps:
      -name:Checkout code
    uses:actions/checkout@v3

    -name:Setup Node.js
    uses: actions/setup-node@v3
    with:
    node-version:'20'

  -name:install dependencies
    uses:npm install

   name:Run tests
   run:npm test
   
    
 

